// src/translations.js

export const dict = {
  en: {
    dashboard: "Dashboard", history: "Credit History", howToUse: "How to Use", settings: "System Settings", theme: "Theme", logout: "Logout", notifs: "Notifications", navNotifs: "Notifs", menu: "Menu", noNotifs: "You have no new notifications.", phoneReq: "Phone Number Required", phoneDesc: "Please link a phone number for SMS alerts.", save: "Save", yourCredit: "Your Credit", curBalance: "Current Balance", payGcash: "Pay via GCash:", name: "Name:", payPerson: "* You may also pay in person directly to the admin.", notifyApp: "Alert Admin (GCash)", textAdmin: "Text Admin (SMS)", noAdminNum: "No Admin #", noBorrowings: "No active borrowings yet.", storageReminder: "Paid credits are auto-archived after 7 days.", yourReceipt: "Your Credit Receipt", savePdf: "Save Receipt as PDF", noCredits: "No recent paid credits.", borrowed: "Borrowed:", paid: "Paid:", accountCleared: "Account Cleared", clearedDesc: "Your balance has been fully paid. Thank you!", awaitingAdmin: "Awaiting Admin Setup", awaitingAdminDesc: "The Admin hasn't created a ledger for your account yet.", proxyLabel: "Optional: Proxy Name (Who picked it up)",
    payReminder: "Formal Notice: Pending Balance", payDesc: "Good day! This is a formal reminder from Uson CreditHub regarding your outstanding balance. Please review your account and kindly settle the amount via GCash or in person. Thank you for your cooperation and prompt action!",
    newCredit: "New Items Added", newCreditDesc: "The Admin has recently added new borrowed items to your ledger.",
    statusGood: "Great standing! No pending balance.", statusWarning: "Your balance is growing. Please pay soon!", statusDanger: "High balance! Please settle your account immediately.",
    htuAppDesc: "What is Uson CreditHub?\nUson CreditHub is a secure digital ledger app designed to replace traditional paper lists for faster, transparent, and organized transactions.", htuUserTitle: "User Guide", htuUser1: "View Debts: Your active borrowings are listed on your Dashboard.", htuUser2: "Pay via GCash: Send your payment to the Admin's GCash, then tap 'Alert Admin' and attach your receipt screenshot.", htuUser3: "Digital Receipts: Go to Credit History to view, download, and save your E-Receipts.", htuAdminTitle: "Admin Guide", htuAdmin1: "Add Entry: Tap the home button to add users or items. Use the built-in calculator for quick math.", htuAdmin2: "Collect Payments: Click a user's name to view their ledger and mark items as paid.", htuAdmin3: "System Tools: Access Analytics, Inventory, and Archives from the Sidebar Menu."
  },
  tl: {
    dashboard: "Dashboard", history: "Mga Nakaraang Transaksyon", howToUse: "Paano Gamitin", settings: "Mga Setting", theme: "Tema", logout: "Mag-logout", notifs: "Mga Notipikasyon", navNotifs: "Notifs", menu: "Menu", noNotifs: "Wala kang bagong notipikasyon.", phoneReq: "Kailangan ng Numero", phoneDesc: "Ilagay ang iyong numero para sa mga SMS alert.", save: "I-save", yourCredit: "Ang Iyong Utang", curBalance: "Kasalukuyang Balanse", payGcash: "Magbayad via GCash:", name: "Pangalan:", payPerson: "* Pwede ring magbayad nang personal sa admin.", notifyApp: "I-alert ang Admin (GCash)", textAdmin: "I-text ang Admin", noAdminNum: "Walang Numero", noBorrowings: "Wala pang utang sa ngayon.", storageReminder: "Awtomatikong ina-archive ang bayad na utang pagkalipas 7 araw.", yourReceipt: "Resibo ng Iyong Utang", savePdf: "I-save ang Resibo (PDF)", noCredits: "Walang bagong bayad na utang.", borrowed: "Inutang:", paid: "Binayaran:", accountCleared: "Bayad Na", clearedDesc: "Ang iyong utang ay bayad na. Maraming salamat!", awaitingAdmin: "Wala Pang Listahan", awaitingAdminDesc: "Hindi pa nagagawa ng Admin ang iyong ledger account.", proxyLabel: "Optional: Pangalan ng kumuha (Proxy)",
    payReminder: "Pormal na Paalala", payDesc: "Magandang araw! Ito ay isang pormal na paalala mula sa Uson CreditHub ukol sa iyong natitirang balanse. Mangyari po lamang na i-check ang iyong account at bayaran ito via GCash o nang personal. Maraming salamat po sa inyong pang-unawa at kooperasyon!",
    newCredit: "May Bagong Utang na Nilista", newCreditDesc: "May idinagdag ang Admin na bagong inutang sa iyong listahan.",
    statusGood: "Maganda ang standing mo! Walang utang.", statusWarning: "Medyo lumalaki na ang utang mo. Magbayad na soon!", statusDanger: "Mataas na ang iyong utang! Paki-settle agad.",
    htuAppDesc: "Ano ang Uson CreditHub?\nAng Uson CreditHub ay isang modernong digital ledger app na idinisenyo upang palitan ang listahan sa papel para sa mas mabilis at malinaw na transaksyon.", htuUserTitle: "Gabay para sa User", htuUser1: "Tingnan ang Utang: Makikita sa Home screen ang mga aktibong utang.", htuUser2: "Magbayad via GCash: I-send ang bayad, pindutin ang 'Alert Admin', at i-attach ang screenshot ng resibo.", htuUser3: "Digital Resibo: Pumunta sa Mga Nakaraang Transaksyon para mai-save ang E-Receipt.", htuAdminTitle: "Gabay para sa Admin", htuAdmin1: "Maglista: Pindutin ang home button para magdagdag. May built-in calculator na rin.", htuAdmin2: "Maningil: Pindutin ang pangalan ng user para makita ang listahan at i-mark as paid ang items.", htuAdmin3: "Mga Tool: Buksan ang menu para sa Analytics, Inventory, and Archives."
  }
};